// import the library
import { library } from '@fortawesome/fontawesome-svg-core';

// import your icons
import {
  faTimes,
  faUserPlus,
  faEdit,
  faTrash,
  faChevronDown,
  faUsersCog,
  faHistory,
  faTachometerAlt,
  faCheck,
  faUserCheck,
  faChevronRight,
  faChevronLeft,
  faExclamationTriangle,
  faTimesCircle,
  faBars,
  faCartPlus,
  faCity,
  faCar,
  faTruckMoving,
  faClock,
  faMapMarkedAlt,
  faSignOutAlt,
  faPlus,
  faMinus,
  faUser,
  faClipboardList,
  faScrewdriver,
  faClipboardCheck,
} from '@fortawesome/free-solid-svg-icons';
import { faEnvelope } from '@fortawesome/free-regular-svg-icons';
import {} from '@fortawesome/free-brands-svg-icons';

library.add(
  faClipboardCheck,
  faMapMarkedAlt,
  faClock,
  faTruckMoving,
  faCar,
  faCity,
  faCartPlus,
  faBars,
  faTimesCircle,
  faExclamationTriangle,
  faChevronDown,
  faCheck,
  faTimes,
  faUser,
  faUserPlus,
  faUsersCog,
  faUserCheck,
  faEdit,
  faTrash,
  faChevronDown,
  faHistory,
  faTachometerAlt,
  faEnvelope,
  faChevronRight,
  faChevronLeft,
  faSignOutAlt,
  faPlus,
  faMinus,
  faClipboardList,
  faScrewdriver
);
